/**
 * world-cities.ts — 世界主要都市データ
 *
 * アストロカートグラフィーのリロケーション評価で使う世界各地の都市。
 * lat: 緯度（北+ / 南-）, lon: 経度（東+ / 西-）。
 */

export interface WorldCity {
  id: string;
  name: string; // 日本語表記
  enName: string;
  country: string; // 日本語の国・地域名
  flag: string; // 国旗絵文字
  lat: number;
  lon: number;
  region: WorldRegion;
}

export type WorldRegion =
  | "japan"
  | "east-asia"
  | "se-asia"
  | "south-asia"
  | "oceania"
  | "middle-east"
  | "europe"
  | "africa"
  | "north-america"
  | "latin-america";

export const REGION_LABEL: Record<WorldRegion, string> = {
  japan: "日本",
  "east-asia": "東アジア",
  "se-asia": "東南アジア",
  "south-asia": "南アジア",
  oceania: "オセアニア",
  "middle-east": "中東",
  europe: "ヨーロッパ",
  africa: "アフリカ",
  "north-america": "北米",
  "latin-america": "中南米",
};

export const WORLD_CITIES: WorldCity[] = [
  // --- 日本 ---
  { id: "tokyo", name: "東京", enName: "Tokyo", country: "日本", flag: "🇯🇵", lat: 35.68, lon: 139.69, region: "japan" },
  { id: "osaka", name: "大阪", enName: "Osaka", country: "日本", flag: "🇯🇵", lat: 34.69, lon: 135.5, region: "japan" },
  { id: "sapporo", name: "札幌", enName: "Sapporo", country: "日本", flag: "🇯🇵", lat: 43.06, lon: 141.35, region: "japan" },
  { id: "fukuoka", name: "福岡", enName: "Fukuoka", country: "日本", flag: "🇯🇵", lat: 33.59, lon: 130.4, region: "japan" },
  { id: "naha", name: "那覇", enName: "Naha", country: "日本", flag: "🇯🇵", lat: 26.21, lon: 127.68, region: "japan" },
  { id: "yokohama", name: "横浜", enName: "Yokohama", country: "日本", flag: "🇯🇵", lat: 35.44, lon: 139.64, region: "japan" },
  { id: "nagoya", name: "名古屋", enName: "Nagoya", country: "日本", flag: "🇯🇵", lat: 35.18, lon: 136.91, region: "japan" },
  { id: "kobe", name: "神戸", enName: "Kobe", country: "日本", flag: "🇯🇵", lat: 34.69, lon: 135.2, region: "japan" },
  { id: "kyoto", name: "京都", enName: "Kyoto", country: "日本", flag: "🇯🇵", lat: 35.01, lon: 135.77, region: "japan" },
  { id: "saitama", name: "さいたま", enName: "Saitama", country: "日本", flag: "🇯🇵", lat: 35.86, lon: 139.65, region: "japan" },
  { id: "kawasaki", name: "川崎", enName: "Kawasaki", country: "日本", flag: "🇯🇵", lat: 35.53, lon: 139.7, region: "japan" },
  { id: "hiroshima", name: "広島", enName: "Hiroshima", country: "日本", flag: "🇯🇵", lat: 34.39, lon: 132.46, region: "japan" },
  { id: "sendai", name: "仙台", enName: "Sendai", country: "日本", flag: "🇯🇵", lat: 38.27, lon: 140.87, region: "japan" },
  { id: "chiba", name: "千葉", enName: "Chiba", country: "日本", flag: "🇯🇵", lat: 35.61, lon: 140.12, region: "japan" },
  { id: "kitakyushu", name: "北九州", enName: "Kitakyushu", country: "日本", flag: "🇯🇵", lat: 33.88, lon: 130.88, region: "japan" },
  { id: "sakai", name: "堺", enName: "Sakai", country: "日本", flag: "🇯🇵", lat: 34.57, lon: 135.48, region: "japan" },
  { id: "niigata", name: "新潟", enName: "Niigata", country: "日本", flag: "🇯🇵", lat: 37.92, lon: 139.04, region: "japan" },
  { id: "hamamatsu", name: "浜松", enName: "Hamamatsu", country: "日本", flag: "🇯🇵", lat: 34.71, lon: 137.73, region: "japan" },
  { id: "kumamoto", name: "熊本", enName: "Kumamoto", country: "日本", flag: "🇯🇵", lat: 32.8, lon: 130.71, region: "japan" },
  { id: "okayama", name: "岡山", enName: "Okayama", country: "日本", flag: "🇯🇵", lat: 34.66, lon: 133.92, region: "japan" },
  { id: "shizuoka", name: "静岡", enName: "Shizuoka", country: "日本", flag: "🇯🇵", lat: 34.98, lon: 138.38, region: "japan" },
  { id: "kanazawa", name: "金沢", enName: "Kanazawa", country: "日本", flag: "🇯🇵", lat: 36.56, lon: 136.66, region: "japan" },
  { id: "kagoshima", name: "鹿児島", enName: "Kagoshima", country: "日本", flag: "🇯🇵", lat: 31.6, lon: 130.56, region: "japan" },
  { id: "utsunomiya", name: "宇都宮", enName: "Utsunomiya", country: "日本", flag: "🇯🇵", lat: 36.56, lon: 139.88, region: "japan" },
  { id: "matsuyama", name: "松山", enName: "Matsuyama", country: "日本", flag: "🇯🇵", lat: 33.84, lon: 132.77, region: "japan" },
  { id: "nagasaki", name: "長崎", enName: "Nagasaki", country: "日本", flag: "🇯🇵", lat: 32.75, lon: 129.87, region: "japan" },
  { id: "takamatsu", name: "高松", enName: "Takamatsu", country: "日本", flag: "🇯🇵", lat: 34.34, lon: 134.05, region: "japan" },
  { id: "toyama", name: "富山", enName: "Toyama", country: "日本", flag: "🇯🇵", lat: 36.7, lon: 137.21, region: "japan" },
  { id: "nagano", name: "長野", enName: "Nagano", country: "日本", flag: "🇯🇵", lat: 36.65, lon: 138.18, region: "japan" },
  { id: "gifu", name: "岐阜", enName: "Gifu", country: "日本", flag: "🇯🇵", lat: 35.42, lon: 136.76, region: "japan" },
  { id: "miyazaki", name: "宮崎", enName: "Miyazaki", country: "日本", flag: "🇯🇵", lat: 31.91, lon: 131.42, region: "japan" },
  { id: "nara", name: "奈良", enName: "Nara", country: "日本", flag: "🇯🇵", lat: 34.69, lon: 135.81, region: "japan" },
  { id: "wakayama", name: "和歌山", enName: "Wakayama", country: "日本", flag: "🇯🇵", lat: 34.23, lon: 135.17, region: "japan" },
  { id: "hakodate", name: "函館", enName: "Hakodate", country: "日本", flag: "🇯🇵", lat: 41.77, lon: 140.73, region: "japan" },
  { id: "aomori", name: "青森", enName: "Aomori", country: "日本", flag: "🇯🇵", lat: 40.82, lon: 140.74, region: "japan" },
  { id: "morioka", name: "盛岡", enName: "Morioka", country: "日本", flag: "🇯🇵", lat: 39.7, lon: 141.15, region: "japan" },
  { id: "akita", name: "秋田", enName: "Akita", country: "日本", flag: "🇯🇵", lat: 39.72, lon: 140.1, region: "japan" },
  { id: "fukushima", name: "福島", enName: "Fukushima", country: "日本", flag: "🇯🇵", lat: 37.76, lon: 140.47, region: "japan" },
  { id: "mito", name: "水戸", enName: "Mito", country: "日本", flag: "🇯🇵", lat: 36.37, lon: 140.47, region: "japan" },
  { id: "maebashi", name: "前橋", enName: "Maebashi", country: "日本", flag: "🇯🇵", lat: 36.39, lon: 139.06, region: "japan" },
  { id: "kofu", name: "甲府", enName: "Kofu", country: "日本", flag: "🇯🇵", lat: 35.66, lon: 138.57, region: "japan" },
  { id: "fukui", name: "福井", enName: "Fukui", country: "日本", flag: "🇯🇵", lat: 36.06, lon: 136.22, region: "japan" },
  { id: "otsu", name: "大津", enName: "Otsu", country: "日本", flag: "🇯🇵", lat: 35.0, lon: 135.87, region: "japan" },
  { id: "tottori", name: "鳥取", enName: "Tottori", country: "日本", flag: "🇯🇵", lat: 35.5, lon: 134.24, region: "japan" },
  { id: "matsue", name: "松江", enName: "Matsue", country: "日本", flag: "🇯🇵", lat: 35.47, lon: 133.05, region: "japan" },
  { id: "yamaguchi", name: "山口", enName: "Yamaguchi", country: "日本", flag: "🇯🇵", lat: 34.19, lon: 131.47, region: "japan" },
  { id: "tokushima", name: "徳島", enName: "Tokushima", country: "日本", flag: "🇯🇵", lat: 34.07, lon: 134.55, region: "japan" },
  { id: "kochi", name: "高知", enName: "Kochi", country: "日本", flag: "🇯🇵", lat: 33.56, lon: 133.53, region: "japan" },
  { id: "saga", name: "佐賀", enName: "Saga", country: "日本", flag: "🇯🇵", lat: 33.26, lon: 130.3, region: "japan" },
  { id: "oita", name: "大分", enName: "Oita", country: "日本", flag: "🇯🇵", lat: 33.24, lon: 131.61, region: "japan" },

  // --- 東アジア ---
  { id: "seoul", name: "ソウル", enName: "Seoul", country: "韓国", flag: "🇰🇷", lat: 37.57, lon: 126.98, region: "east-asia" },
  { id: "jeju", name: "済州島", enName: "Jeju", country: "韓国", flag: "🇰🇷", lat: 33.5, lon: 126.53, region: "east-asia" },
  { id: "busan", name: "釜山", enName: "Busan", country: "韓国", flag: "🇰🇷", lat: 35.18, lon: 129.08, region: "east-asia" },
  { id: "incheon", name: "仁川", enName: "Incheon", country: "韓国", flag: "🇰🇷", lat: 37.46, lon: 126.71, region: "east-asia" },
  { id: "daegu", name: "大邱", enName: "Daegu", country: "韓国", flag: "🇰🇷", lat: 35.87, lon: 128.6, region: "east-asia" },
  { id: "daejeon", name: "大田", enName: "Daejeon", country: "韓国", flag: "🇰🇷", lat: 36.35, lon: 127.38, region: "east-asia" },
  { id: "gwangju", name: "光州", enName: "Gwangju", country: "韓国", flag: "🇰🇷", lat: 35.16, lon: 126.85, region: "east-asia" },
  { id: "ulsan", name: "蔚山", enName: "Ulsan", country: "韓国", flag: "🇰🇷", lat: 35.54, lon: 129.31, region: "east-asia" },
  { id: "beijing", name: "北京", enName: "Beijing", country: "中国", flag: "🇨🇳", lat: 39.9, lon: 116.41, region: "east-asia" },
  { id: "shanghai", name: "上海", enName: "Shanghai", country: "中国", flag: "🇨🇳", lat: 31.23, lon: 121.47, region: "east-asia" },
  { id: "guangzhou", name: "広州", enName: "Guangzhou", country: "中国", flag: "🇨🇳", lat: 23.13, lon: 113.26, region: "east-asia" },
  { id: "shenzhen", name: "深圳", enName: "Shenzhen", country: "中国", flag: "🇨🇳", lat: 22.54, lon: 114.06, region: "east-asia" },
  { id: "chengdu", name: "成都", enName: "Chengdu", country: "中国", flag: "🇨🇳", lat: 30.57, lon: 104.07, region: "east-asia" },
  { id: "chongqing", name: "重慶", enName: "Chongqing", country: "中国", flag: "🇨🇳", lat: 29.56, lon: 106.55, region: "east-asia" },
  { id: "wuhan", name: "武漢", enName: "Wuhan", country: "中国", flag: "🇨🇳", lat: 30.59, lon: 114.31, region: "east-asia" },
  { id: "xian", name: "西安", enName: "Xian", country: "中国", flag: "🇨🇳", lat: 34.34, lon: 108.94, region: "east-asia" },
  { id: "hangzhou", name: "杭州", enName: "Hangzhou", country: "中国", flag: "🇨🇳", lat: 30.27, lon: 120.15, region: "east-asia" },
  { id: "nanjing", name: "南京", enName: "Nanjing", country: "中国", flag: "🇨🇳", lat: 32.06, lon: 118.8, region: "east-asia" },
  { id: "tianjin", name: "天津", enName: "Tianjin", country: "中国", flag: "🇨🇳", lat: 39.13, lon: 117.2, region: "east-asia" },
  { id: "qingdao", name: "青島", enName: "Qingdao", country: "中国", flag: "🇨🇳", lat: 36.07, lon: 120.38, region: "east-asia" },
  { id: "dalian", name: "大連", enName: "Dalian", country: "中国", flag: "🇨🇳", lat: 38.91, lon: 121.61, region: "east-asia" },
  { id: "suzhou", name: "蘇州", enName: "Suzhou", country: "中国", flag: "🇨🇳", lat: 31.3, lon: 120.62, region: "east-asia" },
  { id: "kunming", name: "昆明", enName: "Kunming", country: "中国", flag: "🇨🇳", lat: 25.04, lon: 102.71, region: "east-asia" },
  { id: "guilin", name: "桂林", enName: "Guilin", country: "中国", flag: "🇨🇳", lat: 25.27, lon: 110.29, region: "east-asia" },
  { id: "sanya", name: "三亜", enName: "Sanya", country: "中国", flag: "🇨🇳", lat: 18.25, lon: 109.51, region: "east-asia" },
  { id: "harbin", name: "ハルビン", enName: "Harbin", country: "中国", flag: "🇨🇳", lat: 45.8, lon: 126.53, region: "east-asia" },
  { id: "shenyang", name: "瀋陽", enName: "Shenyang", country: "中国", flag: "🇨🇳", lat: 41.81, lon: 123.43, region: "east-asia" },
  { id: "hongkong", name: "香港", enName: "Hong Kong", country: "中国", flag: "🇭🇰", lat: 22.32, lon: 114.17, region: "east-asia" },
  { id: "macau", name: "マカオ", enName: "Macau", country: "中国", flag: "🇲🇴", lat: 22.2, lon: 113.54, region: "east-asia" },
  { id: "taipei", name: "台北", enName: "Taipei", country: "台湾", flag: "🇹🇼", lat: 25.03, lon: 121.57, region: "east-asia" },
  { id: "kaohsiung", name: "高雄", enName: "Kaohsiung", country: "台湾", flag: "🇹🇼", lat: 22.63, lon: 120.3, region: "east-asia" },
  { id: "taichung", name: "台中", enName: "Taichung", country: "台湾", flag: "🇹🇼", lat: 24.15, lon: 120.67, region: "east-asia" },
  { id: "tainan", name: "台南", enName: "Tainan", country: "台湾", flag: "🇹🇼", lat: 22.99, lon: 120.21, region: "east-asia" },
  { id: "ulaanbaatar", name: "ウランバートル", enName: "Ulaanbaatar", country: "モンゴル", flag: "🇲🇳", lat: 47.89, lon: 106.91, region: "east-asia" },

  // --- 東南アジア ---
  { id: "singapore", name: "シンガポール", enName: "Singapore", country: "シンガポール", flag: "🇸🇬", lat: 1.35, lon: 103.82, region: "se-asia" },
  { id: "bangkok", name: "バンコク", enName: "Bangkok", country: "タイ", flag: "🇹🇭", lat: 13.76, lon: 100.5, region: "se-asia" },
  { id: "chiangmai", name: "チェンマイ", enName: "Chiang Mai", country: "タイ", flag: "🇹🇭", lat: 18.79, lon: 98.99, region: "se-asia" },
  { id: "phuket", name: "プーケット", enName: "Phuket", country: "タイ", flag: "🇹🇭", lat: 7.88, lon: 98.39, region: "se-asia" },
  { id: "pattaya", name: "パタヤ", enName: "Pattaya", country: "タイ", flag: "🇹🇭", lat: 12.93, lon: 100.88, region: "se-asia" },
  { id: "krabi", name: "クラビ", enName: "Krabi", country: "タイ", flag: "🇹🇭", lat: 8.09, lon: 98.91, region: "se-asia" },
  { id: "bali", name: "バリ島", enName: "Bali", country: "インドネシア", flag: "🇮🇩", lat: -8.41, lon: 115.19, region: "se-asia" },
  { id: "jakarta", name: "ジャカルタ", enName: "Jakarta", country: "インドネシア", flag: "🇮🇩", lat: -6.21, lon: 106.85, region: "se-asia" },
  { id: "surabaya", name: "スラバヤ", enName: "Surabaya", country: "インドネシア", flag: "🇮🇩", lat: -7.26, lon: 112.74, region: "se-asia" },
  { id: "yogyakarta", name: "ジョグジャカルタ", enName: "Yogyakarta", country: "インドネシア", flag: "🇮🇩", lat: -7.8, lon: 110.36, region: "se-asia" },
  { id: "bandung", name: "バンドン", enName: "Bandung", country: "インドネシア", flag: "🇮🇩", lat: -6.92, lon: 107.61, region: "se-asia" },
  { id: "makassar", name: "マカッサル", enName: "Makassar", country: "インドネシア", flag: "🇮🇩", lat: -5.15, lon: 119.43, region: "se-asia" },
  { id: "lombok", name: "ロンボク島", enName: "Lombok", country: "インドネシア", flag: "🇮🇩", lat: -8.65, lon: 116.32, region: "se-asia" },
  { id: "kualalumpur", name: "クアラルンプール", enName: "Kuala Lumpur", country: "マレーシア", flag: "🇲🇾", lat: 3.14, lon: 101.69, region: "se-asia" },
  { id: "penang", name: "ペナン", enName: "Penang", country: "マレーシア", flag: "🇲🇾", lat: 5.41, lon: 100.33, region: "se-asia" },
  { id: "kotakinabalu", name: "コタキナバル", enName: "Kota Kinabalu", country: "マレーシア", flag: "🇲🇾", lat: 5.98, lon: 116.07, region: "se-asia" },
  { id: "johorbahru", name: "ジョホールバル", enName: "Johor Bahru", country: "マレーシア", flag: "🇲🇾", lat: 1.49, lon: 103.74, region: "se-asia" },
  { id: "malacca", name: "マラッカ", enName: "Malacca", country: "マレーシア", flag: "🇲🇾", lat: 2.2, lon: 102.25, region: "se-asia" },
  { id: "manila", name: "マニラ", enName: "Manila", country: "フィリピン", flag: "🇵🇭", lat: 14.6, lon: 120.98, region: "se-asia" },
  { id: "cebu", name: "セブ", enName: "Cebu", country: "フィリピン", flag: "🇵🇭", lat: 10.32, lon: 123.9, region: "se-asia" },
  { id: "davao", name: "ダバオ", enName: "Davao", country: "フィリピン", flag: "🇵🇭", lat: 7.07, lon: 125.61, region: "se-asia" },
  { id: "boracay", name: "ボラカイ", enName: "Boracay", country: "フィリピン", flag: "🇵🇭", lat: 11.97, lon: 121.92, region: "se-asia" },
  { id: "hanoi", name: "ハノイ", enName: "Hanoi", country: "ベトナム", flag: "🇻🇳", lat: 21.03, lon: 105.85, region: "se-asia" },
  { id: "hochiminh", name: "ホーチミン", enName: "Ho Chi Minh", country: "ベトナム", flag: "🇻🇳", lat: 10.82, lon: 106.63, region: "se-asia" },
  { id: "danang", name: "ダナン", enName: "Da Nang", country: "ベトナム", flag: "🇻🇳", lat: 16.05, lon: 108.21, region: "se-asia" },
  { id: "hue", name: "フエ", enName: "Hue", country: "ベトナム", flag: "🇻🇳", lat: 16.46, lon: 107.59, region: "se-asia" },
  { id: "hoian", name: "ホイアン", enName: "Hoi An", country: "ベトナム", flag: "🇻🇳", lat: 15.88, lon: 108.34, region: "se-asia" },
  { id: "nhatrang", name: "ニャチャン", enName: "Nha Trang", country: "ベトナム", flag: "🇻🇳", lat: 12.24, lon: 109.19, region: "se-asia" },
  { id: "phnompenh", name: "プノンペン", enName: "Phnom Penh", country: "カンボジア", flag: "🇰🇭", lat: 11.56, lon: 104.92, region: "se-asia" },
  { id: "yangon", name: "ヤンゴン", enName: "Yangon", country: "ミャンマー", flag: "🇲🇲", lat: 16.87, lon: 96.2, region: "se-asia" },
  { id: "mandalay", name: "マンダレー", enName: "Mandalay", country: "ミャンマー", flag: "🇲🇲", lat: 21.96, lon: 96.09, region: "se-asia" },
  { id: "bagan", name: "バガン", enName: "Bagan", country: "ミャンマー", flag: "🇲🇲", lat: 21.17, lon: 94.86, region: "se-asia" },
  { id: "vientiane", name: "ビエンチャン", enName: "Vientiane", country: "ラオス", flag: "🇱🇦", lat: 17.97, lon: 102.63, region: "se-asia" },
  { id: "luangprabang", name: "ルアンパバーン", enName: "Luang Prabang", country: "ラオス", flag: "🇱🇦", lat: 19.89, lon: 102.14, region: "se-asia" },
  { id: "bandarseribegawan", name: "バンダルスリブガワン", enName: "Bandar Seri Begawan", country: "ブルネイ", flag: "🇧🇳", lat: 4.9, lon: 114.94, region: "se-asia" },

  // --- 南アジア ---
  { id: "delhi", name: "デリー", enName: "Delhi", country: "インド", flag: "🇮🇳", lat: 28.61, lon: 77.21, region: "south-asia" },
  { id: "mumbai", name: "ムンバイ", enName: "Mumbai", country: "インド", flag: "🇮🇳", lat: 19.08, lon: 72.88, region: "south-asia" },
  { id: "bangalore", name: "バンガロール", enName: "Bangalore", country: "インド", flag: "🇮🇳", lat: 12.97, lon: 77.59, region: "south-asia" },
  { id: "chennai", name: "チェンナイ", enName: "Chennai", country: "インド", flag: "🇮🇳", lat: 13.08, lon: 80.27, region: "south-asia" },
  { id: "kolkata", name: "コルカタ", enName: "Kolkata", country: "インド", flag: "🇮🇳", lat: 22.57, lon: 88.36, region: "south-asia" },
  { id: "hyderabad", name: "ハイデラバード", enName: "Hyderabad", country: "インド", flag: "🇮🇳", lat: 17.39, lon: 78.49, region: "south-asia" },
  { id: "jaipur", name: "ジャイプル", enName: "Jaipur", country: "インド", flag: "🇮🇳", lat: 26.91, lon: 75.79, region: "south-asia" },
  { id: "goa", name: "ゴア", enName: "Goa", country: "インド", flag: "🇮🇳", lat: 15.3, lon: 74.12, region: "south-asia" },
  { id: "pune", name: "プネー", enName: "Pune", country: "インド", flag: "🇮🇳", lat: 18.52, lon: 73.86, region: "south-asia" },
  { id: "agra", name: "アーグラ", enName: "Agra", country: "インド", flag: "🇮🇳", lat: 27.18, lon: 78.01, region: "south-asia" },
  { id: "ahmedabad", name: "アーメダバード", enName: "Ahmedabad", country: "インド", flag: "🇮🇳", lat: 23.03, lon: 72.58, region: "south-asia" },
  { id: "varanasi", name: "バラナシ", enName: "Varanasi", country: "インド", flag: "🇮🇳", lat: 25.32, lon: 82.97, region: "south-asia" },
  { id: "colombo", name: "コロンボ", enName: "Colombo", country: "スリランカ", flag: "🇱🇰", lat: 6.93, lon: 79.86, region: "south-asia" },
  { id: "kandy", name: "キャンディ", enName: "Kandy", country: "スリランカ", flag: "🇱🇰", lat: 7.29, lon: 80.64, region: "south-asia" },
  { id: "kathmandu", name: "カトマンズ", enName: "Kathmandu", country: "ネパール", flag: "🇳🇵", lat: 27.72, lon: 85.32, region: "south-asia" },
  { id: "pokhara", name: "ポカラ", enName: "Pokhara", country: "ネパール", flag: "🇳🇵", lat: 28.21, lon: 83.99, region: "south-asia" },
  { id: "dhaka", name: "ダッカ", enName: "Dhaka", country: "バングラデシュ", flag: "🇧🇩", lat: 23.81, lon: 90.41, region: "south-asia" },
  { id: "karachi", name: "カラチ", enName: "Karachi", country: "パキスタン", flag: "🇵🇰", lat: 24.86, lon: 67.01, region: "south-asia" },
  { id: "lahore", name: "ラホール", enName: "Lahore", country: "パキスタン", flag: "🇵🇰", lat: 31.55, lon: 74.34, region: "south-asia" },
  { id: "islamabad", name: "イスラマバード", enName: "Islamabad", country: "パキスタン", flag: "🇵🇰", lat: 33.69, lon: 73.06, region: "south-asia" },

  // --- オセアニア ---
  { id: "sydney", name: "シドニー", enName: "Sydney", country: "オーストラリア", flag: "🇦🇺", lat: -33.87, lon: 151.21, region: "oceania" },
  { id: "melbourne", name: "メルボルン", enName: "Melbourne", country: "オーストラリア", flag: "🇦🇺", lat: -37.81, lon: 144.96, region: "oceania" },
  { id: "brisbane", name: "ブリスベン", enName: "Brisbane", country: "オーストラリア", flag: "🇦🇺", lat: -27.47, lon: 153.03, region: "oceania" },
  { id: "perth", name: "パース", enName: "Perth", country: "オーストラリア", flag: "🇦🇺", lat: -31.95, lon: 115.86, region: "oceania" },
  { id: "goldcoast", name: "ゴールドコースト", enName: "Gold Coast", country: "オーストラリア", flag: "🇦🇺", lat: -28.0, lon: 153.43, region: "oceania" },
  { id: "adelaide", name: "アデレード", enName: "Adelaide", country: "オーストラリア", flag: "🇦🇺", lat: -34.93, lon: 138.6, region: "oceania" },
  { id: "canberra", name: "キャンベラ", enName: "Canberra", country: "オーストラリア", flag: "🇦🇺", lat: -35.28, lon: 149.13, region: "oceania" },
  { id: "darwin", name: "ダーウィン", enName: "Darwin", country: "オーストラリア", flag: "🇦🇺", lat: -12.46, lon: 130.84, region: "oceania" },
  { id: "cairns", name: "ケアンズ", enName: "Cairns", country: "オーストラリア", flag: "🇦🇺", lat: -16.92, lon: 145.77, region: "oceania" },
  { id: "hobart", name: "ホバート", enName: "Hobart", country: "オーストラリア", flag: "🇦🇺", lat: -42.88, lon: 147.33, region: "oceania" },
  { id: "auckland", name: "オークランド", enName: "Auckland", country: "ニュージーランド", flag: "🇳🇿", lat: -36.85, lon: 174.76, region: "oceania" },
  { id: "wellington", name: "ウェリントン", enName: "Wellington", country: "ニュージーランド", flag: "🇳🇿", lat: -41.29, lon: 174.78, region: "oceania" },
  { id: "christchurch", name: "クライストチャーチ", enName: "Christchurch", country: "ニュージーランド", flag: "🇳🇿", lat: -43.53, lon: 172.64, region: "oceania" },
  { id: "queenstown", name: "クイーンズタウン", enName: "Queenstown", country: "ニュージーランド", flag: "🇳🇿", lat: -45.03, lon: 168.66, region: "oceania" },
  { id: "honolulu", name: "ホノルル", enName: "Honolulu", country: "ハワイ", flag: "🇺🇸", lat: 21.31, lon: -157.86, region: "oceania" },
  { id: "guam", name: "グアム", enName: "Guam", country: "グアム", flag: "🇬🇺", lat: 13.44, lon: 144.79, region: "oceania" },
  { id: "saipan", name: "サイパン", enName: "Saipan", country: "北マリアナ諸島", flag: "🇲🇵", lat: 15.18, lon: 145.75, region: "oceania" },
  { id: "nadi", name: "ナンディ", enName: "Nadi", country: "フィジー", flag: "🇫🇯", lat: -17.78, lon: 177.42, region: "oceania" },
  { id: "papeete", name: "タヒチ", enName: "Papeete", country: "タヒチ", flag: "🇵🇫", lat: -17.54, lon: -149.57, region: "oceania" },
  { id: "noumea", name: "ヌメア", enName: "Noumea", country: "ニューカレドニア", flag: "🇳🇨", lat: -22.28, lon: 166.46, region: "oceania" },
  { id: "portmoresby", name: "ポートモレスビー", enName: "Port Moresby", country: "パプアニューギニア", flag: "🇵🇬", lat: -9.44, lon: 147.18, region: "oceania" },
  { id: "apia", name: "アピア", enName: "Apia", country: "サモア", flag: "🇼🇸", lat: -13.83, lon: -171.77, region: "oceania" },

  // --- 中東 ---
  { id: "dubai", name: "ドバイ", enName: "Dubai", country: "UAE", flag: "🇦🇪", lat: 25.2, lon: 55.27, region: "middle-east" },
  { id: "abudhabi", name: "アブダビ", enName: "Abu Dhabi", country: "UAE", flag: "🇦🇪", lat: 24.45, lon: 54.38, region: "middle-east" },
  { id: "sharjah", name: "シャルジャ", enName: "Sharjah", country: "UAE", flag: "🇦🇪", lat: 25.35, lon: 55.39, region: "middle-east" },
  { id: "doha", name: "ドーハ", enName: "Doha", country: "カタール", flag: "🇶🇦", lat: 25.29, lon: 51.53, region: "middle-east" },
  { id: "riyadh", name: "リヤド", enName: "Riyadh", country: "サウジアラビア", flag: "🇸🇦", lat: 24.71, lon: 46.68, region: "middle-east" },
  { id: "jeddah", name: "ジッダ", enName: "Jeddah", country: "サウジアラビア", flag: "🇸🇦", lat: 21.49, lon: 39.19, region: "middle-east" },
  { id: "mecca", name: "メッカ", enName: "Mecca", country: "サウジアラビア", flag: "🇸🇦", lat: 21.42, lon: 39.83, region: "middle-east" },
  { id: "muscat", name: "マスカット", enName: "Muscat", country: "オマーン", flag: "🇴🇲", lat: 23.59, lon: 58.41, region: "middle-east" },
  { id: "kuwaitcity", name: "クウェート", enName: "Kuwait City", country: "クウェート", flag: "🇰🇼", lat: 29.38, lon: 47.99, region: "middle-east" },
  { id: "manama", name: "マナーマ", enName: "Manama", country: "バーレーン", flag: "🇧🇭", lat: 26.23, lon: 50.59, region: "middle-east" },
  { id: "amman", name: "アンマン", enName: "Amman", country: "ヨルダン", flag: "🇯🇴", lat: 31.95, lon: 35.93, region: "middle-east" },
  { id: "beirut", name: "ベイルート", enName: "Beirut", country: "レバノン", flag: "🇱🇧", lat: 33.89, lon: 35.5, region: "middle-east" },
  { id: "telaviv", name: "テルアビブ", enName: "Tel Aviv", country: "イスラエル", flag: "🇮🇱", lat: 32.08, lon: 34.78, region: "middle-east" },
  { id: "jerusalem", name: "エルサレム", enName: "Jerusalem", country: "イスラエル", flag: "🇮🇱", lat: 31.77, lon: 35.21, region: "middle-east" },
  { id: "istanbul", name: "イスタンブール", enName: "Istanbul", country: "トルコ", flag: "🇹🇷", lat: 41.01, lon: 28.98, region: "middle-east" },
  { id: "ankara", name: "アンカラ", enName: "Ankara", country: "トルコ", flag: "🇹🇷", lat: 39.93, lon: 32.87, region: "middle-east" },
  { id: "izmir", name: "イズミル", enName: "Izmir", country: "トルコ", flag: "🇹🇷", lat: 38.42, lon: 27.14, region: "middle-east" },
  { id: "antalya", name: "アンタルヤ", enName: "Antalya", country: "トルコ", flag: "🇹🇷", lat: 36.9, lon: 30.69, region: "middle-east" },
  { id: "cappadocia", name: "カッパドキア", enName: "Cappadocia", country: "トルコ", flag: "🇹🇷", lat: 38.64, lon: 34.83, region: "middle-east" },
  { id: "tehran", name: "テヘラン", enName: "Tehran", country: "イラン", flag: "🇮🇷", lat: 35.69, lon: 51.39, region: "middle-east" },
  { id: "isfahan", name: "イスファハン", enName: "Isfahan", country: "イラン", flag: "🇮🇷", lat: 32.65, lon: 51.67, region: "middle-east" },
  { id: "shiraz", name: "シーラーズ", enName: "Shiraz", country: "イラン", flag: "🇮🇷", lat: 29.59, lon: 52.58, region: "middle-east" },
  { id: "baghdad", name: "バグダッド", enName: "Baghdad", country: "イラク", flag: "🇮🇶", lat: 33.31, lon: 44.36, region: "middle-east" },

  // --- ヨーロッパ ---
  { id: "london", name: "ロンドン", enName: "London", country: "イギリス", flag: "🇬🇧", lat: 51.51, lon: -0.13, region: "europe" },
  { id: "manchester", name: "マンチェスター", enName: "Manchester", country: "イギリス", flag: "🇬🇧", lat: 53.48, lon: -2.24, region: "europe" },
  { id: "edinburgh", name: "エディンバラ", enName: "Edinburgh", country: "イギリス", flag: "🇬🇧", lat: 55.95, lon: -3.19, region: "europe" },
  { id: "liverpool", name: "リバプール", enName: "Liverpool", country: "イギリス", flag: "🇬🇧", lat: 53.41, lon: -2.99, region: "europe" },
  { id: "glasgow", name: "グラスゴー", enName: "Glasgow", country: "イギリス", flag: "🇬🇧", lat: 55.86, lon: -4.25, region: "europe" },
  { id: "paris", name: "パリ", enName: "Paris", country: "フランス", flag: "🇫🇷", lat: 48.86, lon: 2.35, region: "europe" },
  { id: "nice", name: "ニース", enName: "Nice", country: "フランス", flag: "🇫🇷", lat: 43.7, lon: 7.27, region: "europe" },
  { id: "lyon", name: "リヨン", enName: "Lyon", country: "フランス", flag: "🇫🇷", lat: 45.76, lon: 4.84, region: "europe" },
  { id: "marseille", name: "マルセイユ", enName: "Marseille", country: "フランス", flag: "🇫🇷", lat: 43.3, lon: 5.37, region: "europe" },
  { id: "bordeaux", name: "ボルドー", enName: "Bordeaux", country: "フランス", flag: "🇫🇷", lat: 44.84, lon: -0.58, region: "europe" },
  { id: "toulouse", name: "トゥールーズ", enName: "Toulouse", country: "フランス", flag: "🇫🇷", lat: 43.6, lon: 1.44, region: "europe" },
  { id: "strasbourg", name: "ストラスブール", enName: "Strasbourg", country: "フランス", flag: "🇫🇷", lat: 48.58, lon: 7.75, region: "europe" },
  { id: "cannes", name: "カンヌ", enName: "Cannes", country: "フランス", flag: "🇫🇷", lat: 43.55, lon: 7.02, region: "europe" },
  { id: "berlin", name: "ベルリン", enName: "Berlin", country: "ドイツ", flag: "🇩🇪", lat: 52.52, lon: 13.41, region: "europe" },
  { id: "munich", name: "ミュンヘン", enName: "Munich", country: "ドイツ", flag: "🇩🇪", lat: 48.14, lon: 11.58, region: "europe" },
  { id: "frankfurt", name: "フランクフルト", enName: "Frankfurt", country: "ドイツ", flag: "🇩🇪", lat: 50.11, lon: 8.68, region: "europe" },
  { id: "hamburg", name: "ハンブルク", enName: "Hamburg", country: "ドイツ", flag: "🇩🇪", lat: 53.55, lon: 9.99, region: "europe" },
  { id: "cologne", name: "ケルン", enName: "Cologne", country: "ドイツ", flag: "🇩🇪", lat: 50.94, lon: 6.96, region: "europe" },
  { id: "stuttgart", name: "シュトゥットガルト", enName: "Stuttgart", country: "ドイツ", flag: "🇩🇪", lat: 48.78, lon: 9.18, region: "europe" },
  { id: "dusseldorf", name: "デュッセルドルフ", enName: "Dusseldorf", country: "ドイツ", flag: "🇩🇪", lat: 51.23, lon: 6.78, region: "europe" },
  { id: "dresden", name: "ドレスデン", enName: "Dresden", country: "ドイツ", flag: "🇩🇪", lat: 51.05, lon: 13.74, region: "europe" },
  { id: "amsterdam", name: "アムステルダム", enName: "Amsterdam", country: "オランダ", flag: "🇳🇱", lat: 52.37, lon: 4.9, region: "europe" },
  { id: "rotterdam", name: "ロッテルダム", enName: "Rotterdam", country: "オランダ", flag: "🇳🇱", lat: 51.92, lon: 4.48, region: "europe" },
  { id: "thehague", name: "ハーグ", enName: "The Hague", country: "オランダ", flag: "🇳🇱", lat: 52.08, lon: 4.3, region: "europe" },
  { id: "brussels", name: "ブリュッセル", enName: "Brussels", country: "ベルギー", flag: "🇧🇪", lat: 50.85, lon: 4.35, region: "europe" },
  { id: "antwerp", name: "アントワープ", enName: "Antwerp", country: "ベルギー", flag: "🇧🇪", lat: 51.22, lon: 4.4, region: "europe" },
  { id: "bruges", name: "ブルージュ", enName: "Bruges", country: "ベルギー", flag: "🇧🇪", lat: 51.21, lon: 3.22, region: "europe" },
  { id: "rome", name: "ローマ", enName: "Rome", country: "イタリア", flag: "🇮🇹", lat: 41.9, lon: 12.5, region: "europe" },
  { id: "milan", name: "ミラノ", enName: "Milan", country: "イタリア", flag: "🇮🇹", lat: 45.46, lon: 9.19, region: "europe" },
  { id: "florence", name: "フィレンツェ", enName: "Florence", country: "イタリア", flag: "🇮🇹", lat: 43.77, lon: 11.26, region: "europe" },
  { id: "venice", name: "ヴェネツィア", enName: "Venice", country: "イタリア", flag: "🇮🇹", lat: 45.44, lon: 12.32, region: "europe" },
  { id: "naples", name: "ナポリ", enName: "Naples", country: "イタリア", flag: "🇮🇹", lat: 40.85, lon: 14.27, region: "europe" },
  { id: "turin", name: "トリノ", enName: "Turin", country: "イタリア", flag: "🇮🇹", lat: 45.07, lon: 7.69, region: "europe" },
  { id: "bologna", name: "ボローニャ", enName: "Bologna", country: "イタリア", flag: "🇮🇹", lat: 44.49, lon: 11.34, region: "europe" },
  { id: "genoa", name: "ジェノヴァ", enName: "Genoa", country: "イタリア", flag: "🇮🇹", lat: 44.41, lon: 8.93, region: "europe" },
  { id: "palermo", name: "パレルモ", enName: "Palermo", country: "イタリア", flag: "🇮🇹", lat: 38.12, lon: 13.36, region: "europe" },
  { id: "barcelona", name: "バルセロナ", enName: "Barcelona", country: "スペイン", flag: "🇪🇸", lat: 41.39, lon: 2.17, region: "europe" },
  { id: "madrid", name: "マドリード", enName: "Madrid", country: "スペイン", flag: "🇪🇸", lat: 40.42, lon: -3.7, region: "europe" },
  { id: "seville", name: "セビリア", enName: "Seville", country: "スペイン", flag: "🇪🇸", lat: 37.39, lon: -5.99, region: "europe" },
  { id: "valencia", name: "バレンシア", enName: "Valencia", country: "スペイン", flag: "🇪🇸", lat: 39.47, lon: -0.38, region: "europe" },
  { id: "bilbao", name: "ビルバオ", enName: "Bilbao", country: "スペイン", flag: "🇪🇸", lat: 43.26, lon: -2.93, region: "europe" },
  { id: "malaga", name: "マラガ", enName: "Malaga", country: "スペイン", flag: "🇪🇸", lat: 36.72, lon: -4.42, region: "europe" },
  { id: "granada", name: "グラナダ", enName: "Granada", country: "スペイン", flag: "🇪🇸", lat: 37.18, lon: -3.6, region: "europe" },
  { id: "ibiza", name: "イビサ", enName: "Ibiza", country: "スペイン", flag: "🇪🇸", lat: 38.91, lon: 1.43, region: "europe" },
  { id: "lisbon", name: "リスボン", enName: "Lisbon", country: "ポルトガル", flag: "🇵🇹", lat: 38.72, lon: -9.14, region: "europe" },
  { id: "porto", name: "ポルト", enName: "Porto", country: "ポルトガル", flag: "🇵🇹", lat: 41.16, lon: -8.62, region: "europe" },
  { id: "zurich", name: "チューリッヒ", enName: "Zurich", country: "スイス", flag: "🇨🇭", lat: 47.37, lon: 8.54, region: "europe" },
  { id: "geneva", name: "ジュネーブ", enName: "Geneva", country: "スイス", flag: "🇨🇭", lat: 46.2, lon: 6.14, region: "europe" },
  { id: "basel", name: "バーゼル", enName: "Basel", country: "スイス", flag: "🇨🇭", lat: 47.56, lon: 7.59, region: "europe" },
  { id: "bern", name: "ベルン", enName: "Bern", country: "スイス", flag: "🇨🇭", lat: 46.95, lon: 7.45, region: "europe" },
  { id: "lucerne", name: "ルツェルン", enName: "Lucerne", country: "スイス", flag: "🇨🇭", lat: 47.05, lon: 8.31, region: "europe" },
  { id: "vienna", name: "ウィーン", enName: "Vienna", country: "オーストリア", flag: "🇦🇹", lat: 48.21, lon: 16.37, region: "europe" },
  { id: "salzburg", name: "ザルツブルク", enName: "Salzburg", country: "オーストリア", flag: "🇦🇹", lat: 47.81, lon: 13.05, region: "europe" },
  { id: "innsbruck", name: "インスブルック", enName: "Innsbruck", country: "オーストリア", flag: "🇦🇹", lat: 47.27, lon: 11.39, region: "europe" },
  { id: "prague", name: "プラハ", enName: "Prague", country: "チェコ", flag: "🇨🇿", lat: 50.08, lon: 14.44, region: "europe" },
  { id: "brno", name: "ブルノ", enName: "Brno", country: "チェコ", flag: "🇨🇿", lat: 49.2, lon: 16.61, region: "europe" },
  { id: "warsaw", name: "ワルシャワ", enName: "Warsaw", country: "ポーランド", flag: "🇵🇱", lat: 52.23, lon: 21.01, region: "europe" },
  { id: "krakow", name: "クラクフ", enName: "Krakow", country: "ポーランド", flag: "🇵🇱", lat: 50.06, lon: 19.94, region: "europe" },
  { id: "wroclaw", name: "ヴロツワフ", enName: "Wroclaw", country: "ポーランド", flag: "🇵🇱", lat: 51.11, lon: 17.04, region: "europe" },
  { id: "budapest", name: "ブダペスト", enName: "Budapest", country: "ハンガリー", flag: "🇭🇺", lat: 47.5, lon: 19.04, region: "europe" },
  { id: "athens", name: "アテネ", enName: "Athens", country: "ギリシャ", flag: "🇬🇷", lat: 37.98, lon: 23.73, region: "europe" },
  { id: "thessaloniki", name: "テッサロニキ", enName: "Thessaloniki", country: "ギリシャ", flag: "🇬🇷", lat: 40.64, lon: 22.94, region: "europe" },
  { id: "santorini", name: "サントリーニ", enName: "Santorini", country: "ギリシャ", flag: "🇬🇷", lat: 36.39, lon: 25.46, region: "europe" },
  { id: "mykonos", name: "ミコノス", enName: "Mykonos", country: "ギリシャ", flag: "🇬🇷", lat: 37.45, lon: 25.33, region: "europe" },
  { id: "zagreb", name: "ザグレブ", enName: "Zagreb", country: "クロアチア", flag: "🇭🇷", lat: 45.81, lon: 15.98, region: "europe" },
  { id: "dubrovnik", name: "ドゥブロヴニク", enName: "Dubrovnik", country: "クロアチア", flag: "🇭🇷", lat: 42.65, lon: 18.09, region: "europe" },
  { id: "split", name: "スプリト", enName: "Split", country: "クロアチア", flag: "🇭🇷", lat: 43.51, lon: 16.44, region: "europe" },
  { id: "copenhagen", name: "コペンハーゲン", enName: "Copenhagen", country: "デンマーク", flag: "🇩🇰", lat: 55.68, lon: 12.57, region: "europe" },
  { id: "stockholm", name: "ストックホルム", enName: "Stockholm", country: "スウェーデン", flag: "🇸🇪", lat: 59.33, lon: 18.07, region: "europe" },
  { id: "gothenburg", name: "イェーテボリ", enName: "Gothenburg", country: "スウェーデン", flag: "🇸🇪", lat: 57.71, lon: 11.97, region: "europe" },
  { id: "malmo", name: "マルメ", enName: "Malmo", country: "スウェーデン", flag: "🇸🇪", lat: 55.6, lon: 13.0, region: "europe" },
  { id: "oslo", name: "オスロ", enName: "Oslo", country: "ノルウェー", flag: "🇳🇴", lat: 59.91, lon: 10.75, region: "europe" },
  { id: "bergen", name: "ベルゲン", enName: "Bergen", country: "ノルウェー", flag: "🇳🇴", lat: 60.39, lon: 5.32, region: "europe" },
  { id: "tromso", name: "トロムソ", enName: "Tromso", country: "ノルウェー", flag: "🇳🇴", lat: 69.65, lon: 18.96, region: "europe" },
  { id: "helsinki", name: "ヘルシンキ", enName: "Helsinki", country: "フィンランド", flag: "🇫🇮", lat: 60.17, lon: 24.94, region: "europe" },
  { id: "dublin", name: "ダブリン", enName: "Dublin", country: "アイルランド", flag: "🇮🇪", lat: 53.35, lon: -6.26, region: "europe" },
  { id: "cork", name: "コーク", enName: "Cork", country: "アイルランド", flag: "🇮🇪", lat: 51.9, lon: -8.47, region: "europe" },
  { id: "galway", name: "ゴールウェイ", enName: "Galway", country: "アイルランド", flag: "🇮🇪", lat: 53.27, lon: -9.06, region: "europe" },
  { id: "reykjavik", name: "レイキャビク", enName: "Reykjavik", country: "アイスランド", flag: "🇮🇸", lat: 64.15, lon: -21.94, region: "europe" },
  { id: "moscow", name: "モスクワ", enName: "Moscow", country: "ロシア", flag: "🇷🇺", lat: 55.76, lon: 37.62, region: "europe" },
  { id: "stpetersburg", name: "サンクトペテルブルク", enName: "St. Petersburg", country: "ロシア", flag: "🇷🇺", lat: 59.93, lon: 30.34, region: "europe" },
  { id: "vladivostok", name: "ウラジオストク", enName: "Vladivostok", country: "ロシア", flag: "🇷🇺", lat: 43.12, lon: 131.89, region: "europe" },
  { id: "sochi", name: "ソチ", enName: "Sochi", country: "ロシア", flag: "🇷🇺", lat: 43.6, lon: 39.73, region: "europe" },
  { id: "bucharest", name: "ブカレスト", enName: "Bucharest", country: "ルーマニア", flag: "🇷🇴", lat: 44.43, lon: 26.1, region: "europe" },
  { id: "sofia", name: "ソフィア", enName: "Sofia", country: "ブルガリア", flag: "🇧🇬", lat: 42.7, lon: 23.32, region: "europe" },
  { id: "belgrade", name: "ベオグラード", enName: "Belgrade", country: "セルビア", flag: "🇷🇸", lat: 44.79, lon: 20.45, region: "europe" },
  { id: "ljubljana", name: "リュブリャナ", enName: "Ljubljana", country: "スロベニア", flag: "🇸🇮", lat: 46.06, lon: 14.51, region: "europe" },
  { id: "tallinn", name: "タリン", enName: "Tallinn", country: "エストニア", flag: "🇪🇪", lat: 59.44, lon: 24.75, region: "europe" },
  { id: "riga", name: "リガ", enName: "Riga", country: "ラトビア", flag: "🇱🇻", lat: 56.95, lon: 24.11, region: "europe" },
  { id: "vilnius", name: "ヴィリニュス", enName: "Vilnius", country: "リトアニア", flag: "🇱🇹", lat: 54.69, lon: 25.28, region: "europe" },
  { id: "kyiv", name: "キーウ", enName: "Kyiv", country: "ウクライナ", flag: "🇺🇦", lat: 50.45, lon: 30.52, region: "europe" },
  { id: "valletta", name: "バレッタ", enName: "Valletta", country: "マルタ", flag: "🇲🇹", lat: 35.9, lon: 14.51, region: "europe" },
  { id: "luxembourg", name: "ルクセンブルク", enName: "Luxembourg", country: "ルクセンブルク", flag: "🇱🇺", lat: 49.61, lon: 6.13, region: "europe" },
  { id: "monaco", name: "モナコ", enName: "Monaco", country: "モナコ", flag: "🇲🇨", lat: 43.74, lon: 7.42, region: "europe" },

  // --- アフリカ ---
  { id: "cairo", name: "カイロ", enName: "Cairo", country: "エジプト", flag: "🇪🇬", lat: 30.04, lon: 31.24, region: "africa" },
  { id: "alexandria", name: "アレクサンドリア", enName: "Alexandria", country: "エジプト", flag: "🇪🇬", lat: 31.2, lon: 29.92, region: "africa" },
  { id: "luxor", name: "ルクソール", enName: "Luxor", country: "エジプト", flag: "🇪🇬", lat: 25.69, lon: 32.64, region: "africa" },
  { id: "sharmelsheikh", name: "シャルムエルシェイク", enName: "Sharm El Sheikh", country: "エジプト", flag: "🇪🇬", lat: 27.92, lon: 34.33, region: "africa" },
  { id: "casablanca", name: "カサブランカ", enName: "Casablanca", country: "モロッコ", flag: "🇲🇦", lat: 33.57, lon: -7.59, region: "africa" },
  { id: "marrakech", name: "マラケシュ", enName: "Marrakech", country: "モロッコ", flag: "🇲🇦", lat: 31.63, lon: -7.98, region: "africa" },
  { id: "fez", name: "フェズ", enName: "Fez", country: "モロッコ", flag: "🇲🇦", lat: 34.02, lon: -5.0, region: "africa" },
  { id: "tangier", name: "タンジェ", enName: "Tangier", country: "モロッコ", flag: "🇲🇦", lat: 35.76, lon: -5.83, region: "africa" },
  { id: "tunis", name: "チュニス", enName: "Tunis", country: "チュニジア", flag: "🇹🇳", lat: 36.81, lon: 10.18, region: "africa" },
  { id: "capetown", name: "ケープタウン", enName: "Cape Town", country: "南アフリカ", flag: "🇿🇦", lat: -33.92, lon: 18.42, region: "africa" },
  { id: "johannesburg", name: "ヨハネスブルグ", enName: "Johannesburg", country: "南アフリカ", flag: "🇿🇦", lat: -26.2, lon: 28.05, region: "africa" },
  { id: "durban", name: "ダーバン", enName: "Durban", country: "南アフリカ", flag: "🇿🇦", lat: -29.86, lon: 31.02, region: "africa" },
  { id: "pretoria", name: "プレトリア", enName: "Pretoria", country: "南アフリカ", flag: "🇿🇦", lat: -25.75, lon: 28.19, region: "africa" },
  { id: "nairobi", name: "ナイロビ", enName: "Nairobi", country: "ケニア", flag: "🇰🇪", lat: -1.29, lon: 36.82, region: "africa" },
  { id: "mombasa", name: "モンバサ", enName: "Mombasa", country: "ケニア", flag: "🇰🇪", lat: -4.04, lon: 39.67, region: "africa" },
  { id: "daressalaam", name: "ダルエスサラーム", enName: "Dar es Salaam", country: "タンザニア", flag: "🇹🇿", lat: -6.79, lon: 39.21, region: "africa" },
  { id: "zanzibar", name: "ザンジバル", enName: "Zanzibar", country: "タンザニア", flag: "🇹🇿", lat: -6.16, lon: 39.2, region: "africa" },
  { id: "arusha", name: "アルーシャ", enName: "Arusha", country: "タンザニア", flag: "🇹🇿", lat: -3.37, lon: 36.68, region: "africa" },
  { id: "addisababa", name: "アディスアベバ", enName: "Addis Ababa", country: "エチオピア", flag: "🇪🇹", lat: 9.03, lon: 38.74, region: "africa" },
  { id: "accra", name: "アクラ", enName: "Accra", country: "ガーナ", flag: "🇬🇭", lat: 5.6, lon: -0.19, region: "africa" },
  { id: "lagos", name: "ラゴス", enName: "Lagos", country: "ナイジェリア", flag: "🇳🇬", lat: 6.52, lon: 3.38, region: "africa" },
  { id: "dakar", name: "ダカール", enName: "Dakar", country: "セネガル", flag: "🇸🇳", lat: 14.72, lon: -17.47, region: "africa" },
  { id: "kigali", name: "キガリ", enName: "Kigali", country: "ルワンダ", flag: "🇷🇼", lat: -1.94, lon: 30.06, region: "africa" },
  { id: "kampala", name: "カンパラ", enName: "Kampala", country: "ウガンダ", flag: "🇺🇬", lat: 0.35, lon: 32.58, region: "africa" },
  { id: "victoriafalls", name: "ヴィクトリアフォールズ", enName: "Victoria Falls", country: "ジンバブエ", flag: "🇿🇼", lat: -17.92, lon: 25.84, region: "africa" },
  { id: "gaborone", name: "ハボローネ", enName: "Gaborone", country: "ボツワナ", flag: "🇧🇼", lat: -24.65, lon: 25.91, region: "africa" },
  { id: "windhoek", name: "ウィントフック", enName: "Windhoek", country: "ナミビア", flag: "🇳🇦", lat: -22.56, lon: 17.08, region: "africa" },
  { id: "seychelles", name: "セーシェル", enName: "Seychelles", country: "セーシェル", flag: "🇸🇨", lat: -4.62, lon: 55.45, region: "africa" },
  { id: "antananarivo", name: "アンタナナリボ", enName: "Antananarivo", country: "マダガスカル", flag: "🇲🇬", lat: -18.88, lon: 47.51, region: "africa" },
  { id: "mauritius", name: "モーリシャス", enName: "Mauritius", country: "モーリシャス", flag: "🇲🇺", lat: -20.35, lon: 57.55, region: "africa" },

  // --- 北米 ---
  { id: "newyork", name: "ニューヨーク", enName: "New York", country: "アメリカ", flag: "🇺🇸", lat: 40.71, lon: -74.01, region: "north-america" },
  { id: "losangeles", name: "ロサンゼルス", enName: "Los Angeles", country: "アメリカ", flag: "🇺🇸", lat: 34.05, lon: -118.24, region: "north-america" },
  { id: "sanfrancisco", name: "サンフランシスコ", enName: "San Francisco", country: "アメリカ", flag: "🇺🇸", lat: 37.77, lon: -122.42, region: "north-america" },
  { id: "seattle", name: "シアトル", enName: "Seattle", country: "アメリカ", flag: "🇺🇸", lat: 47.61, lon: -122.33, region: "north-america" },
  { id: "chicago", name: "シカゴ", enName: "Chicago", country: "アメリカ", flag: "🇺🇸", lat: 41.88, lon: -87.63, region: "north-america" },
  { id: "lasvegas", name: "ラスベガス", enName: "Las Vegas", country: "アメリカ", flag: "🇺🇸", lat: 36.17, lon: -115.14, region: "north-america" },
  { id: "miami", name: "マイアミ", enName: "Miami", country: "アメリカ", flag: "🇺🇸", lat: 25.76, lon: -80.19, region: "north-america" },
  { id: "boston", name: "ボストン", enName: "Boston", country: "アメリカ", flag: "🇺🇸", lat: 42.36, lon: -71.06, region: "north-america" },
  { id: "washington", name: "ワシントンD.C.", enName: "Washington D.C.", country: "アメリカ", flag: "🇺🇸", lat: 38.91, lon: -77.04, region: "north-america" },
  { id: "austin", name: "オースティン", enName: "Austin", country: "アメリカ", flag: "🇺🇸", lat: 30.27, lon: -97.74, region: "north-america" },
  { id: "houston", name: "ヒューストン", enName: "Houston", country: "アメリカ", flag: "🇺🇸", lat: 29.76, lon: -95.37, region: "north-america" },
  { id: "dallas", name: "ダラス", enName: "Dallas", country: "アメリカ", flag: "🇺🇸", lat: 32.78, lon: -96.8, region: "north-america" },
  { id: "phoenix", name: "フェニックス", enName: "Phoenix", country: "アメリカ", flag: "🇺🇸", lat: 33.45, lon: -112.07, region: "north-america" },
  { id: "sandiego", name: "サンディエゴ", enName: "San Diego", country: "アメリカ", flag: "🇺🇸", lat: 32.72, lon: -117.16, region: "north-america" },
  { id: "sanjose", name: "サンノゼ", enName: "San Jose", country: "アメリカ", flag: "🇺🇸", lat: 37.34, lon: -121.89, region: "north-america" },
  { id: "portland", name: "ポートランド", enName: "Portland", country: "アメリカ", flag: "🇺🇸", lat: 45.52, lon: -122.68, region: "north-america" },
  { id: "denver", name: "デンバー", enName: "Denver", country: "アメリカ", flag: "🇺🇸", lat: 39.74, lon: -104.99, region: "north-america" },
  { id: "atlanta", name: "アトランタ", enName: "Atlanta", country: "アメリカ", flag: "🇺🇸", lat: 33.75, lon: -84.39, region: "north-america" },
  { id: "philadelphia", name: "フィラデルフィア", enName: "Philadelphia", country: "アメリカ", flag: "🇺🇸", lat: 39.95, lon: -75.17, region: "north-america" },
  { id: "orlando", name: "オーランド", enName: "Orlando", country: "アメリカ", flag: "🇺🇸", lat: 28.54, lon: -81.38, region: "north-america" },
  { id: "neworleans", name: "ニューオーリンズ", enName: "New Orleans", country: "アメリカ", flag: "🇺🇸", lat: 29.95, lon: -90.07, region: "north-america" },
  { id: "nashville", name: "ナッシュビル", enName: "Nashville", country: "アメリカ", flag: "🇺🇸", lat: 36.16, lon: -86.78, region: "north-america" },
  { id: "saltlakecity", name: "ソルトレイクシティ", enName: "Salt Lake City", country: "アメリカ", flag: "🇺🇸", lat: 40.76, lon: -111.89, region: "north-america" },
  { id: "minneapolis", name: "ミネアポリス", enName: "Minneapolis", country: "アメリカ", flag: "🇺🇸", lat: 44.98, lon: -93.27, region: "north-america" },
  { id: "detroit", name: "デトロイト", enName: "Detroit", country: "アメリカ", flag: "🇺🇸", lat: 42.33, lon: -83.05, region: "north-america" },
  { id: "sacramento", name: "サクラメント", enName: "Sacramento", country: "アメリカ", flag: "🇺🇸", lat: 38.58, lon: -121.49, region: "north-america" },
  { id: "sanantonio", name: "サンアントニオ", enName: "San Antonio", country: "アメリカ", flag: "🇺🇸", lat: 29.42, lon: -98.49, region: "north-america" },
  { id: "charlotte", name: "シャーロット", enName: "Charlotte", country: "アメリカ", flag: "🇺🇸", lat: 35.23, lon: -80.84, region: "north-america" },
  { id: "pittsburgh", name: "ピッツバーグ", enName: "Pittsburgh", country: "アメリカ", flag: "🇺🇸", lat: 40.44, lon: -79.996, region: "north-america" },
  { id: "anchorage", name: "アンカレッジ", enName: "Anchorage", country: "アメリカ", flag: "🇺🇸", lat: 61.22, lon: -149.9, region: "north-america" },
  { id: "sedona", name: "セドナ", enName: "Sedona", country: "アメリカ", flag: "🇺🇸", lat: 34.87, lon: -111.76, region: "north-america" },
  { id: "santafe", name: "サンタフェ", enName: "Santa Fe", country: "アメリカ", flag: "🇺🇸", lat: 35.69, lon: -105.94, region: "north-america" },
  { id: "kansascity", name: "カンザスシティ", enName: "Kansas City", country: "アメリカ", flag: "🇺🇸", lat: 39.1, lon: -94.58, region: "north-america" },
  { id: "stlouis", name: "セントルイス", enName: "St. Louis", country: "アメリカ", flag: "🇺🇸", lat: 38.63, lon: -90.2, region: "north-america" },
  { id: "tampa", name: "タンパ", enName: "Tampa", country: "アメリカ", flag: "🇺🇸", lat: 27.95, lon: -82.46, region: "north-america" },
  { id: "baltimore", name: "ボルチモア", enName: "Baltimore", country: "アメリカ", flag: "🇺🇸", lat: 39.29, lon: -76.61, region: "north-america" },
  { id: "cleveland", name: "クリーブランド", enName: "Cleveland", country: "アメリカ", flag: "🇺🇸", lat: 41.5, lon: -81.69, region: "north-america" },
  { id: "memphis", name: "メンフィス", enName: "Memphis", country: "アメリカ", flag: "🇺🇸", lat: 35.15, lon: -90.05, region: "north-america" },
  { id: "savannah", name: "サバンナ", enName: "Savannah", country: "アメリカ", flag: "🇺🇸", lat: 32.08, lon: -81.09, region: "north-america" },
  { id: "palmsprings", name: "パームスプリングス", enName: "Palm Springs", country: "アメリカ", flag: "🇺🇸", lat: 33.83, lon: -116.55, region: "north-america" },
  { id: "indianapolis", name: "インディアナポリス", enName: "Indianapolis", country: "アメリカ", flag: "🇺🇸", lat: 39.77, lon: -86.16, region: "north-america" },
  { id: "milwaukee", name: "ミルウォーキー", enName: "Milwaukee", country: "アメリカ", flag: "🇺🇸", lat: 43.04, lon: -87.91, region: "north-america" },
  { id: "raleigh", name: "ローリー", enName: "Raleigh", country: "アメリカ", flag: "🇺🇸", lat: 35.78, lon: -78.64, region: "north-america" },
  { id: "jacksonville", name: "ジャクソンビル", enName: "Jacksonville", country: "アメリカ", flag: "🇺🇸", lat: 30.33, lon: -81.66, region: "north-america" },
  { id: "vancouver", name: "バンクーバー", enName: "Vancouver", country: "カナダ", flag: "🇨🇦", lat: 49.28, lon: -123.12, region: "north-america" },
  { id: "toronto", name: "トロント", enName: "Toronto", country: "カナダ", flag: "🇨🇦", lat: 43.65, lon: -79.38, region: "north-america" },
  { id: "montreal", name: "モントリオール", enName: "Montreal", country: "カナダ", flag: "🇨🇦", lat: 45.5, lon: -73.57, region: "north-america" },
  { id: "calgary", name: "カルガリー", enName: "Calgary", country: "カナダ", flag: "🇨🇦", lat: 51.05, lon: -114.07, region: "north-america" },
  { id: "edmonton", name: "エドモントン", enName: "Edmonton", country: "カナダ", flag: "🇨🇦", lat: 53.55, lon: -113.49, region: "north-america" },
  { id: "ottawa", name: "オタワ", enName: "Ottawa", country: "カナダ", flag: "🇨🇦", lat: 45.42, lon: -75.7, region: "north-america" },
  { id: "quebeccity", name: "ケベックシティ", enName: "Quebec City", country: "カナダ", flag: "🇨🇦", lat: 46.81, lon: -71.21, region: "north-america" },
  { id: "winnipeg", name: "ウィニペグ", enName: "Winnipeg", country: "カナダ", flag: "🇨🇦", lat: 49.9, lon: -97.14, region: "north-america" },
  { id: "halifax", name: "ハリファックス", enName: "Halifax", country: "カナダ", flag: "🇨🇦", lat: 44.65, lon: -63.58, region: "north-america" },
  { id: "victoria", name: "ビクトリア", enName: "Victoria", country: "カナダ", flag: "🇨🇦", lat: 48.43, lon: -123.37, region: "north-america" },
  { id: "mexicocity", name: "メキシコシティ", enName: "Mexico City", country: "メキシコ", flag: "🇲🇽", lat: 19.43, lon: -99.13, region: "north-america" },
  { id: "cancun", name: "カンクン", enName: "Cancun", country: "メキシコ", flag: "🇲🇽", lat: 21.16, lon: -86.85, region: "north-america" },
  { id: "guadalajara", name: "グアダラハラ", enName: "Guadalajara", country: "メキシコ", flag: "🇲🇽", lat: 20.68, lon: -103.35, region: "north-america" },
  { id: "monterrey", name: "モンテレイ", enName: "Monterrey", country: "メキシコ", flag: "🇲🇽", lat: 25.69, lon: -100.32, region: "north-america" },
  { id: "tijuana", name: "ティファナ", enName: "Tijuana", country: "メキシコ", flag: "🇲🇽", lat: 32.51, lon: -117.04, region: "north-america" },
  { id: "oaxaca", name: "オアハカ", enName: "Oaxaca", country: "メキシコ", flag: "🇲🇽", lat: 17.07, lon: -96.73, region: "north-america" },
  { id: "puertovallarta", name: "プエルトバジャルタ", enName: "Puerto Vallarta", country: "メキシコ", flag: "🇲🇽", lat: 20.65, lon: -105.23, region: "north-america" },
  { id: "tulum", name: "トゥルム", enName: "Tulum", country: "メキシコ", flag: "🇲🇽", lat: 20.21, lon: -87.47, region: "north-america" },

  // --- 中南米 ---
  { id: "saopaulo", name: "サンパウロ", enName: "Sao Paulo", country: "ブラジル", flag: "🇧🇷", lat: -23.55, lon: -46.63, region: "latin-america" },
  { id: "riodejaneiro", name: "リオデジャネイロ", enName: "Rio de Janeiro", country: "ブラジル", flag: "🇧🇷", lat: -22.91, lon: -43.17, region: "latin-america" },
  { id: "brasilia", name: "ブラジリア", enName: "Brasilia", country: "ブラジル", flag: "🇧🇷", lat: -15.79, lon: -47.88, region: "latin-america" },
  { id: "salvador", name: "サルバドール", enName: "Salvador", country: "ブラジル", flag: "🇧🇷", lat: -12.97, lon: -38.51, region: "latin-america" },
  { id: "recife", name: "レシフェ", enName: "Recife", country: "ブラジル", flag: "🇧🇷", lat: -8.05, lon: -34.88, region: "latin-america" },
  { id: "fortaleza", name: "フォルタレザ", enName: "Fortaleza", country: "ブラジル", flag: "🇧🇷", lat: -3.73, lon: -38.52, region: "latin-america" },
  { id: "manaus", name: "マナウス", enName: "Manaus", country: "ブラジル", flag: "🇧🇷", lat: -3.12, lon: -60.02, region: "latin-america" },
  { id: "florianopolis", name: "フロリアノポリス", enName: "Florianopolis", country: "ブラジル", flag: "🇧🇷", lat: -27.6, lon: -48.55, region: "latin-america" },
  { id: "buenosaires", name: "ブエノスアイレス", enName: "Buenos Aires", country: "アルゼンチン", flag: "🇦🇷", lat: -34.6, lon: -58.38, region: "latin-america" },
  { id: "cordoba", name: "コルドバ", enName: "Cordoba", country: "アルゼンチン", flag: "🇦🇷", lat: -31.42, lon: -64.18, region: "latin-america" },
  { id: "mendoza", name: "メンドーサ", enName: "Mendoza", country: "アルゼンチン", flag: "🇦🇷", lat: -32.89, lon: -68.85, region: "latin-america" },
  { id: "bariloche", name: "バリローチェ", enName: "Bariloche", country: "アルゼンチン", flag: "🇦🇷", lat: -41.13, lon: -71.31, region: "latin-america" },
  { id: "ushuaia", name: "ウシュアイア", enName: "Ushuaia", country: "アルゼンチン", flag: "🇦🇷", lat: -54.8, lon: -68.3, region: "latin-america" },
  { id: "santiago", name: "サンティアゴ", enName: "Santiago", country: "チリ", flag: "🇨🇱", lat: -33.45, lon: -70.67, region: "latin-america" },
  { id: "valparaiso", name: "バルパライソ", enName: "Valparaiso", country: "チリ", flag: "🇨🇱", lat: -33.05, lon: -71.62, region: "latin-america" },
  { id: "lima", name: "リマ", enName: "Lima", country: "ペルー", flag: "🇵🇪", lat: -12.05, lon: -77.04, region: "latin-america" },
  { id: "cusco", name: "クスコ", enName: "Cusco", country: "ペルー", flag: "🇵🇪", lat: -13.53, lon: -71.97, region: "latin-america" },
  { id: "arequipa", name: "アレキパ", enName: "Arequipa", country: "ペルー", flag: "🇵🇪", lat: -16.41, lon: -71.54, region: "latin-america" },
  { id: "bogota", name: "ボゴタ", enName: "Bogota", country: "コロンビア", flag: "🇨🇴", lat: 4.71, lon: -74.07, region: "latin-america" },
  { id: "medellin", name: "メデジン", enName: "Medellin", country: "コロンビア", flag: "🇨🇴", lat: 6.24, lon: -75.57, region: "latin-america" },
  { id: "cartagena", name: "カルタヘナ", enName: "Cartagena", country: "コロンビア", flag: "🇨🇴", lat: 10.42, lon: -75.55, region: "latin-america" },
  { id: "quito", name: "キト", enName: "Quito", country: "エクアドル", flag: "🇪🇨", lat: -0.18, lon: -78.47, region: "latin-america" },
  { id: "galapagos", name: "ガラパゴス", enName: "Galapagos", country: "エクアドル", flag: "🇪🇨", lat: -0.74, lon: -90.31, region: "latin-america" },
  { id: "lapaz", name: "ラパス", enName: "La Paz", country: "ボリビア", flag: "🇧🇴", lat: -16.5, lon: -68.15, region: "latin-america" },
  { id: "uyuni", name: "ウユニ", enName: "Uyuni", country: "ボリビア", flag: "🇧🇴", lat: -20.46, lon: -66.83, region: "latin-america" },
  { id: "montevideo", name: "モンテビデオ", enName: "Montevideo", country: "ウルグアイ", flag: "🇺🇾", lat: -34.9, lon: -56.16, region: "latin-america" },
  { id: "asuncion", name: "アスンシオン", enName: "Asuncion", country: "パラグアイ", flag: "🇵🇾", lat: -25.28, lon: -57.63, region: "latin-america" },
  { id: "caracas", name: "カラカス", enName: "Caracas", country: "ベネズエラ", flag: "🇻🇪", lat: 10.49, lon: -66.88, region: "latin-america" },
  { id: "sanjosecr", name: "サンホセ", enName: "San Jose", country: "コスタリカ", flag: "🇨🇷", lat: 9.93, lon: -84.08, region: "latin-america" },
  { id: "panamacity", name: "パナマシティ", enName: "Panama City", country: "パナマ", flag: "🇵🇦", lat: 8.98, lon: -79.52, region: "latin-america" },
  { id: "guatemalacity", name: "グアテマラシティ", enName: "Guatemala City", country: "グアテマラ", flag: "🇬🇹", lat: 14.63, lon: -90.51, region: "latin-america" },
  { id: "havana", name: "ハバナ", enName: "Havana", country: "キューバ", flag: "🇨🇺", lat: 23.11, lon: -82.37, region: "latin-america" },
  { id: "kingston", name: "キングストン", enName: "Kingston", country: "ジャマイカ", flag: "🇯🇲", lat: 17.97, lon: -76.79, region: "latin-america" },
  { id: "santodomingo", name: "サントドミンゴ", enName: "Santo Domingo", country: "ドミニカ共和国", flag: "🇩🇴", lat: 18.49, lon: -69.93, region: "latin-america" },
  { id: "puntacana", name: "プンタカナ", enName: "Punta Cana", country: "ドミニカ共和国", flag: "🇩🇴", lat: 18.58, lon: -68.4, region: "latin-america" },
  { id: "sanjuan", name: "サンフアン", enName: "San Juan", country: "プエルトリコ", flag: "🇵🇷", lat: 18.47, lon: -66.11, region: "latin-america" },
  { id: "nassau", name: "ナッソー", enName: "Nassau", country: "バハマ", flag: "🇧🇸", lat: 25.06, lon: -77.34, region: "latin-america" },
  { id: "sanpedrosula", name: "サンペドロスーラ", enName: "San Pedro Sula", country: "ホンジュラス", flag: "🇭🇳", lat: 15.5, lon: -88.03, region: "latin-america" },
];

export function getCityById(id: string): WorldCity | undefined {
  return WORLD_CITIES.find((c) => c.id === id);
}
